# .coderabbit.yaml
reviews:
  # Options: "chill", "assertive"
  profile: "chill"
  # Enable/Disable the high-level summary of changes
  high_level_summary: true
  # Enable/Disable line-by-line code suggestions
  review_status: true
